11:12:12 PM:ERROR [conexion.py:27] Ocurrio un error: name 'psycopg2' is not defined
11:12:23 PM:ERROR [conexion.py:27] Ocurrio un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

